version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '[%(levelname)s] %(name)s {%(pathname)s:%(lineno)d} %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  '':
    level: INFO
    handlers:
      - default
