version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(levelname)s] %(name)s {%(pathname)s:%(lineno)d} %(message)s'
handlers:
  stream:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    formatter: simple
    class: logging.RotatingFileHandler
    filename: /app/logs/app.log
    mode: a
    maxBytes: 1048576
loggers:
  '':
    level: INFO
    handlers:
      - file
